### ISSUE TITLE
Formatter Plugin crashing with Elixir 1.13.0

### ISSUE THREAD

**Issue by maennchen** [surface-ui/surface_formatter#52]
## Versions

* Elixir: `1.13.0`
* Erlang: `24.1.6`
* surface: `0.6.1`
* surface_formatter: `0.7.1`

## Error

```
mix format failed for file: lib/hygeia_web/live/statistics_live/export.sface
** (FunctionClauseError) no function clause matching in Inspect.Algebra.format/2    
    
    The following arguments were given to Inspect.Algebra.format/2:
    
        # 1
        {:doc_group, {:doc_cons, {:doc_string, "gettext", 7}, {:doc_group, {:doc_cons, {:doc_cons, {:doc_cons, {:doc_nest, {:doc_cons, "(", {:doc_break, "", :strict}}, 2, :break}, {:doc_cons, {:doc_nest, {:doc_cons, {:doc_cons, "\"", {:doc_string, "From", 4}}, "\""}, 2, :break}, {:doc_break, "", :strict}}}, ")"}, :doc_nil}, :self}}, :self}
    
        # 2
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        def format(doc, width) when is_binary(doc) or doc === :doc_nil or doc === :doc_line or is_tuple(doc) and elem(doc, 0) === :doc_break or elem(doc, 0) === :doc_collapse or elem(doc, 0) === :doc_color or elem(doc, 0) === :doc_cons or elem(doc, 0) === :doc_fits or elem(doc, 0) === :doc_force or elem(doc, 0) === :doc_group or elem(doc, 0) === :doc_nest or elem(doc, 0) === :doc_string and width == :infinity or is_integer(width) and width >= 0
    
    (elixir 1.13.0) lib/inspect/algebra.ex:958: Inspect.Algebra.format/2
    lib/surface/formatter/phases/render.ex:38: Surface.Formatter.Phases.Render.render_node/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    lib/surface/formatter/phases/render.ex:183: Surface.Formatter.Phases.Render.render_node/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    lib/surface/formatter/phases/render.ex:183: Surface.Formatter.Phases.Render.render_node/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
```

See in CI: https://github.com/jshmrtn/hygeia/runs/4412768200?check_suite_focus=true

## Config

```
[
  import_deps: [:phoenix, :phoenix_live_view, :surface, :ecto, :ecto_enum],
  inputs: [
    ".dialyzer_ignore.exs",
    ".formatter.exs",
    "*.{ex,exs}",
    "priv/*/seeds.exs",
    "priv/repo/seeds/*.exs",
    "{config,lib,test}/**/*.{ex,exs,sface}"
  ],
  subdirectories: ["priv/*/migrations"],
  plugins: [Surface.Formatter.Plugin]
]
```

**Comment by paulstatezny** [comment]
@maennchen Thanks for the report! I'll look into this soon. It was working with the release candidate.

**Comment by paulstatezny** [comment]
Can you provide the stack trace of the crash?

**Comment by maennchen** [comment]
@paulstatezny I think that is in the original issue description.

**Comment by capitalist** [comment]
It is, might be helpful to have the snippet from export.sface it choked on as well - is that shareable?

**Comment by paulstatezny** [comment]
It wasn't appearing on my phone for some reason; thanks!

**Comment by paulstatezny** [comment]
> It is, might be helpful to have the snippet from export.sface it choked on as well - is that shareable?

@maennchen Agreed – if it's private, perhaps you could put it in a https://gist.github.com/ and send me the link? @paulstatezny on Elixir Slack or my email's in my GitHub profile.

**Comment by paulstatezny** [comment]
Another question: Does `mix surface.format` succeed? At first glance, this looks like it might be unrelated to using the Formatter Plugin and generally a problem with the formatter.

**Comment by doughsay** [comment]
I just ran into this as well.  Here's the error:

```
mix format failed for file: lib/ambry_web/live/admin/book_live/form_component.sface
** (FunctionClauseError) no function clause matching in Inspect.Algebra.format/2

    The following arguments were given to Inspect.Algebra.format/2:

        # 1
        {:doc_group, {:doc_cons, "@", {:doc_string, "title", 5}}, :self}

        # 2
        nil

    Attempted function clauses (showing 1 out of 1):

        def format(doc, width) when is_binary(doc) or doc === :doc_nil or doc === :doc_line or is_tuple(doc) and elem(doc, 0) === :doc_break or elem(doc, 0) === :doc_collapse or elem(doc, 0) === :doc_color or elem(doc, 0) === :doc_cons or elem(doc, 0) === :doc_fits or elem(doc, 0) === :doc_force or elem(doc, 0) === :doc_group or elem(doc, 0) === :doc_nest or elem(doc, 0) === :doc_string and width == :infinity or is_integer(width) and width >= 0

    (elixir 1.13.0) lib/inspect/algebra.ex:958: Inspect.Algebra.format/2
    lib/surface/formatter/phases/render.ex:36: Surface.Formatter.Phases.Render.render_node/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    lib/surface/formatter/phases/render.ex:178: Surface.Formatter.Phases.Render.render_node/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    lib/surface/formatter/phases/render.ex:178: Surface.Formatter.Phases.Render.render_node/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
```

It appears `width` is being passed as `nil` to `format(doc, width)` and the guards want it to be either an integer or `:infinity`.

So this made me think that adding the `:line_length` option to `.formatter.exs` would maybe help, and 🎉 it does 😅. So I added `line_length: 120` to my config file and the error goes away.

**Comment by paulstatezny** [comment]
@doughsay Extremely helpful analysis. Thanks y'all!

Working on a patch, hope to have it released shortly.

**Comment by paulstatezny** [comment]
Thanks again @maennchen and @doughsay !

Released in 0.7.2 – https://hex.pm/packages/surface_formatter/0.7.2

**Comment by maennchen** [comment]
Works like a charm. Thanks a lot 🙂

**Comment by capitalist** [comment]
wow, you all fixed that fast ![](https://media1.giphy.com/media/xUPGcjQ6dJEjH5uwMw/giphy-downsized-medium.gif)
